import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/Footer";
import { FavoritesProvider } from "@/contexts/FavoritesContext";

export const metadata: Metadata = {
  title: "Moon Ceramic & Furniture Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FavoritesProvider>
          <Navbar />
          <div className="flex-1">{children}</div>
          <Footer />
        </FavoritesProvider>
      </body>
    </html>
  );
}
